(function(a){function l(){g=function(b){return m+"-"+b};j=function(b){return m+"-"+b};e=function(b){return b+"."+m};a.each([g,j,e],function(b,c){c.add=function(h){h=h.split(" ");for(var k in h)c[h[k]]=c(h[k])}});g.add("touch desktop scale-1 scale-2 scale-3 wrapper opened opening fixed inline hover slider slide loading noanimation fastanimation");j.add("slide anchor");e.add("open opening close closing prev next slideTo sliding click pinch scroll resize orientationchange load loading loaded transitionend webkitTransitionEnd");
f={complObject:function(b,c){a.isPlainObject(b)||(b=c);return b},complBoolean:function(b,c){if(typeof b!="boolean")b=c;return b},complNumber:function(b,c){a.isNumeric(b)||(b=c);return b},complString:function(b,c){if(typeof b!="string")b=c;return b},isPercentage:function(b){return typeof b=="string"&&b.slice(-1)=="%"},getPercentage:function(b){return parseInt(b.slice(0,-1))},resizeRatio:function(b,c,h,k,n){var o=c.width();c=c.height();if(h&&o>h)o=h;if(k&&c>k)c=k;if(o/c<n)c=o/n;else o=c*n;b.width(o).height(c)},
transitionend:function(b,c,h){var k=false,n=function(){k||c.call(b[0]);k=true};b.one(e.transitionend,n);b.one(e.webkitTransitionEnd,n);setTimeout(n,h*1.1)},setViewportScale:function(){if(i.viewportScale){var b=i.viewportScale.getScale();if(typeof b!="undefined"){b=1/b;i.$body.removeClass(g["scale-1"]).removeClass(g["scale-2"]).removeClass(g["scale-3"]).addClass(g["scale-"+Math.max(Math.min(Math.round(b),3),1)])}}}};i={$wndw:a(window),$html:a("html"),$body:a("body"),scrollPosition:0,viewportScale:null,
viewportScaleInterval:null};i.$body.addClass(a[d].support.touch?g.touch:g.desktop);i.$wndw.on(e.scroll,function(b){if(i.$body.hasClass(g.opened)){window.scrollTo(0,i.scrollPosition);b.preventDefault();b.stopPropagation();b.stopImmediatePropagation()}});if(!i.viewportScale&&a[d].support.touch&&typeof FlameViewportScale!="undefined"){i.viewportScale=new FlameViewportScale;f.setViewportScale();i.$wndw.on(e.orientationchange+" "+e.resize,function(){if(i.viewportScaleInterval){clearTimeout(i.viewportScaleInterval);
i.viewportScaleInterval=null}i.viewportScaleInterval=setTimeout(function(){f.setViewportScale()},500)})}a[d]._c=g;a[d]._d=j;a[d]._e=e;a[d]._f=f;a[d]._g=i}var d="tosrus",m="tos";if(!a[d]){var g={},j={},e={},f={},i={};a[d]=function(b,c,h){this.$node=b;this.opts=c;this.conf=h;this.vars={};this.nodes={};this.slides={};this._init();return this};a[d].prototype={_init:function(){var b=this;this._complementOptions();this.vars.fixed=this.opts.wrapper.target=="window";this.nodes.$wrpr=a('<div class="'+g.wrapper+
'" />');this.nodes.$sldr=a('<div class="'+g.slider+'" />').appendTo(this.nodes.$wrpr);this.nodes.$wrpr.addClass(this.vars.fixed?g.fixed:g.inline).addClass(g("fx-"+this.opts.effect)).addClass(g(this.opts.slides.scale)).addClass(this.opts.wrapper.classes);this.nodes.$wrpr.on(e.open+" "+e.close+" "+e.prev+" "+e.next+" "+e.slideTo,function(h){arguments=Array.prototype.slice.call(arguments);h=arguments.shift();var k=h.type;h.stopPropagation();typeof b[k]=="function"&&b[k].apply(b,arguments)}).on(e.opening+
" "+e.closing+" "+e.sliding+" "+e.loading+" "+e.loaded,function(h){h.stopPropagation()}).on(e.click,function(h){h.stopPropagation();switch(b.opts.wrapper.onClick){case "toggleUI":b.nodes.$wrpr.toggleClass(g.hover);break;case "close":b.close();break}});this.nodes.$anchors=this._initAnchors();this.nodes.$slides=this._initSlides();this.slides.total=this.nodes.$slides.length;this.slides.visible=this.opts.slides.visible;this.slides.index=0;this.vars.opened=true;for(var c=0;c<a[d].addons.length;c++)a.isFunction(this["_addon_"+
a[d].addons[c]])&&this["_addon_"+a[d].addons[c]]();for(c=0;c<a[d].ui.length;c++)this.nodes.$wrpr.find("."+g[a[d].ui[c]]).length&&this.nodes.$wrpr.addClass(g("has-"+a[d].ui[c]));if(this.vars.fixed){this.nodes.$wrpr.appendTo(i.$body);this.close(true)}else{this.nodes.$wrpr.appendTo(this.opts.wrapper.target);if(this.opts.show){this.vars.opened=false;this.open(0,true)}else this.close(true)}},open:function(b,c){var h=this;if(!this.vars.opened){if(this.vars.fixed){i.scrollPosition=i.$wndw.scrollTop();i.$body.addClass(g.opened);
f.setViewportScale()}c?this.nodes.$wrpr.addClass(g.opening).trigger(e.opening,[b,c]):setTimeout(function(){h.nodes.$wrpr.addClass(g.opening).trigger(e.opening,[b,c])},5);this.nodes.$wrpr.addClass(g.hover).addClass(g.opened)}this.vars.opened=true;this._loadContents();if(a.isNumeric(b)){c=c||!this.vars.opened;this.slideTo(b,c)}},close:function(b){if(this.vars.opened){this.vars.fixed&&i.$body.removeClass(g.opened);b?this.nodes.$wrpr.removeClass(g.opened):f.transitionend(this.nodes.$wrpr,function(){a(this).removeClass(g.opened)},
this.conf.transitionDuration);this.nodes.$wrpr.removeClass(g.hover).removeClass(g.opening).trigger(e.closing,[this.slides.index,b])}this.vars.opened=false},prev:function(b,c){if(!a.isNumeric(b))b=this.opts.slides.slide;this.slideTo(this.slides.index-b,c)},next:function(b,c){if(!a.isNumeric(b))b=this.opts.slides.slide;this.slideTo(this.slides.index+b,c)},slideTo:function(b,c){if(!this.vars.opened)return false;if(!a.isNumeric(b))return false;var h=true;if(b<0){var k=this.slides.index==0;if(this.opts.infinite)b=
k?this.slides.total-this.slides.visible:0;else{b=0;if(k)h=false}}if(b+this.slides.visible>this.slides.total){k=this.slides.index+this.slides.visible>=this.slides.total;if(this.opts.infinite)b=k?0:this.slides.total-this.slides.visible;else{b=this.slides.total-this.slides.visible;if(k)h=false}}this.slides.index=b;this._loadContents();if(h){h=0-this.slides.index*this.opts.slides.width+this.opts.slides.offset;if(this.slides.widthPercentage)h+="%";if(c){this.nodes.$sldr.addClass(g.noanimation);f.transitionend(this.nodes.$sldr,
function(){a(this).removeClass(g.noanimation)},5)}for(var n in a[d].effects)if(n==this.opts.effect){a[d].effects[n].call(this,h,c);break}this.nodes.$wrpr.trigger(e.sliding,[b,c])}},_initAnchors:function(){var b=this,c=a();if(this.$node.is("a"))for(var h in a[d].media)c=c.add(this.$node.filter(function(){return a[d].media[h].filterAnchors.call(b,a(this).attr("href"))}));return c},_initSlides:function(){this[this.$node.is("a")?"_initSlidesFromAnchors":"_initSlidesFromContent"]();return this.nodes.$sldr.children().css("width",
this.opts.slides.width+(this.slides.widthPercentage?"%":"px"))},_initSlidesFromAnchors:function(){var b=this;this.nodes.$anchors.each(function(c){var h=a(this),k=a('<div class="'+g.slide+" "+g.loading+'" />').data(j.anchor,h).appendTo(b.nodes.$sldr);h.data(j.slide,k).on(e.click,function(n){n.preventDefault();b.open(c)})})},_initSlidesFromContent:function(){var b=this;this.$node.children().each(function(){var c=a(this);a('<div class="'+g.slide+'" />').append(c).appendTo(b.nodes.$sldr);for(var h in a[d].media)if(a[d].media[h].filterSlides.call(b,
c)){a[d].media[h].initSlides.call(b,c);c.parent().addClass(g(h));break}})},_loadContents:function(){var b=this;switch(this.opts.slides.load){case "all":this._loadContent(0,this.slides.total);break;case "visible":this._loadContent(this.slides.index,this.slides.index+this.slides.visible);break;case "near-visible":default:this._loadContent(this.slides.index,this.slides.index+this.slides.visible);setTimeout(function(){b._loadContent(b.slides.index-b.slides.visible,b.slides.index);b._loadContent(b.slides.index+
b.slides.visible,b.slides.index+b.slides.visible*2)},this.conf.transitionDuration);break}},_loadContent:function(b,c){var h=this;this.nodes.$slides.slice(b,c).each(function(){var k=a(this);if(k.children().length==0){var n=k.data(j.anchor).attr("href");for(var o in a[d].media)if(a[d].media[o].filterAnchors.call(h,n)){a[d].media[o].initAnchors.call(h,k,n);k.addClass(g(o));break}k.trigger(e.loading,[k.data(j.anchor)])}})},_complementOptions:function(){if(typeof this.opts.wrapper.target=="undefined")this.opts.wrapper.target=
this.$node.is("a")?"window":this.$node;if(this.opts.wrapper.target!="window")if(typeof this.opts.wrapper.target=="string")this.opts.wrapper.target=a(this.opts.wrapper.target);this.opts.show=f.complBoolean(this.opts.show,this.opts.wrapper.target!="window");if(a.isNumeric(this.opts.slides.width)){this.slides.widthPercentage=false;this.opts.slides.visible=f.complNumber(this.opts.slides.visible,1)}else{var b=f.isPercentage(this.opts.slides.width)?f.getPercentage(this.opts.slides.width):false;this.slides.widthPercentage=
true;this.opts.slides.visible=f.complNumber(this.opts.slides.visible,b?Math.floor(100/b):1);this.opts.slides.width=b?b:Math.ceil(1E4/this.opts.slides.visible)/100}this.opts.slides.slide=f.complNumber(this.opts.slides.slide,this.opts.slides.visible);this.opts.slides.offset=f.isPercentage(this.opts.slides.offset)?f.getPercentage(this.opts.slides.offset):f.complNumber(this.opts.slides.offset,0)},_uniqueID:function(){if(!this.__uniqueID)this.__uniqueID=0;this.__uniqueID++;return g("uid-"+this.__uniqueID)}};
a.fn[d]=function(b,c,h,k){i.$wndw||l();b=a.extend(true,{},a[d].defaults,b);b=a.extend(true,{},b,a[d].support.touch?h:c);k=a.extend(true,{},a[d].configuration,k);b=new a[d](this,b,k);this.data(d,b);return b.nodes.$wrpr};a[d].support={touch:"ontouchstart"in window.document};a[d].defaults={infinite:false,effect:"slide",wrapper:{classes:"",onClick:"toggleUI"},slides:{offset:0,scale:"fit",load:"near-visible",visible:1}};a[d].configuration={transitionDuration:400};a[d].constants={};a[d].debug=function(){};
a[d].deprecated=function(b,c){typeof console!="undefined"&&typeof console.warn!="undefined"&&console.warn(d+": "+b+" is deprecated, use "+c+" instead.")};a[d].effects={slide:function(b){this.nodes.$sldr.css("left",b)},fade:function(b){f.transitionend(this.nodes.$sldr,function(){a(this).css("left",b).css("opacity",1)},this.conf.transitionDuration);this.nodes.$sldr.css("opacity",0)}};a[d].version="2.2.2";a[d].media={};a[d].addons=[];a[d].ui=[]}})(jQuery);
(function(a){function l(e,f){return a('<a class="'+g[e]+""+f+'" href="#"><span></span></a>')}function d(e,f,i,b){f.on(j.click,function(c){c.preventDefault();c.stopPropagation();e.trigger(j[i],[b])})}var m=false,g,j;a.tosrus.prototype._addon_buttons=function(){if(!m){g=a.tosrus._c;j=a.tosrus._e;g.add("prev next close disabled");m=true}var e=this,f=this.opts.buttons;this.nodes.$prev=null;this.nodes.$next=null;this.nodes.$clse=null;if(typeof f=="boolean"||typeof f=="string"&&f=="inline")f={prev:f,next:f};
if(typeof f.close=="undefined")f.close=this.vars.fixed;if(this.nodes.$slides.length<2){f.prev=false;f.next=false}a.each({prev:"prev",next:"next",close:"clse"},function(i,b){if(f[i])if(typeof f[i]=="string"&&f[i]=="inline")e.vars.fixed&&i!="close"&&e.nodes.$slides.on(j.loading,function(){var c=l(i," "+g.inline)[i=="prev"?"prependTo":"appendTo"](this);d(e.nodes.$wrpr,c,i,1);if(!e.opts.infinite)if(i=="prev"&&a(this).is(":first-child")||i=="next"&&a(this).is(":last-child"))c.addClass(g.disabled)});else{if(typeof f[i]==
"string")f[i]=a(f[i]);e.nodes["$"+b]=f[i]instanceof a?f[i]:l(i,"").appendTo(e.nodes.$wrpr);d(e.nodes.$wrpr,e.nodes["$"+b],i,null)}});if(!this.opts.infinite){this.updateButtons();this.nodes.$wrpr.on(j.sliding,function(){e.updateButtons()})}};a.tosrus.prototype.updateButtons=function(){if(this.nodes.$prev)this.nodes.$prev[(this.slides.index<1?"add":"remove")+"Class"](g.disabled);if(this.nodes.$next)this.nodes.$next[(this.slides.index>=this.slides.total-this.slides.visible?"add":"remove")+"Class"](g.disabled)};
a.tosrus.defaults.buttons={prev:!a.tosrus.support.touch,next:!a.tosrus.support.touch};a.tosrus.addons.push("buttons");a.tosrus.ui.push("prev");a.tosrus.ui.push("next");a.tosrus.ui.push("close")})(jQuery);
(function(a){var l=false,d,m,g;a.tosrus.prototype._addon_caption=function(){if(!l){d=a.tosrus._c;m=a.tosrus._d;g=a.tosrus._e;d.add("caption uibg");m.add("caption");l=true}var j=this,e=this.opts.caption;if(e.add){e.attributes=e.attributes||[];if(typeof e.target=="string")e.target=a(e.target);if(e.target instanceof a)this.nodes.$capt=e.target;else{this.nodes.$capt=a('<div class="'+d.caption+'" />').appendTo(this.nodes.$wrpr);if(!this.nodes.$uibg)this.nodes.$uibg=a('<div class="'+d.uibg+'" />').prependTo(this.nodes.$wrpr)}for(var f=
0,i=this.slides.visible;f<i;f++)a('<div class="'+d.caption+"-"+f+'" />').css("width",this.opts.slides.width+(this.slides.widthPercentage?"%":"px")).appendTo(this.nodes.$capt);this.nodes.$slides.each(function(){var b=a(this),c=j.vars.fixed?b.data(m.anchor):b.children();b.data(m.caption,"");for(var h=0,k=e.attributes.length;h<k;h++){var n=c.attr(e.attributes[h]);if(n&&n.length){b.data(m.caption,n);break}}});this.nodes.$wrpr.on(g.sliding,function(){for(var b=0,c=j.slides.visible;b<c;b++)j.nodes.$capt.children().eq(b).text(j.nodes.$sldr.children().eq(j.slides.index+
b).data(m.caption)||"")})}};a.tosrus.defaults.caption={add:false,target:null,attributes:["title","alt","rel"]};a.tosrus.addons.push("caption");a.tosrus.ui.push("caption")})(jQuery);
(function(a){if(typeof Hammer=="function"){var l=false,d,m,g;a.tosrus.prototype._addon_drag=function(){if(!l){d=a.tosrus._c;m=a.tosrus._e;g=a.tosrus._f;l=true}var j=this;if(this.opts.drag&&this.opts.effect=="slide")if(Hammer.VERSION<2)a.tosrus.deprecated("Older version of the Hammer library","version 2 or newer");else if(this.nodes.$slides.length>1){var e=0,f=false,i=false;(new Hammer(this.nodes.$wrpr[0])).on("panstart panleft panright panend swipeleft swiperight",function(b){b.preventDefault()}).on("panstart",
function(){j.nodes.$sldr.addClass(d.noanimation)}).on("panleft panright",function(b){e=b.deltaX;i=false;switch(b.direction){case 2:f="left";break;case 4:f="right";break;default:f=false;break}if(f=="left"&&j.slides.index+j.slides.visible>=j.slides.total||f=="right"&&j.slides.index==0)e/=2.5;j.nodes.$sldr.css("margin-left",Math.round(e))}).on("swipeleft swiperight",function(){i=true}).on("panend",function(){j.nodes.$sldr.removeClass(d.noanimation).addClass(d.fastanimation);g.transitionend(j.nodes.$sldr,
function(){j.nodes.$sldr.removeClass(d.fastanimation)},j.conf.transitionDuration/2);j.nodes.$sldr.css("margin-left",0);if(f=="left"||f=="right"){if(i)var b=j.slides.visible;else{b=j.nodes.$slides.first().width();b=Math.floor((Math.abs(e)+b/2)/b)}if(b>0)j.nodes.$wrpr.trigger(m[f=="left"?"next":"prev"],[b])}f=false})}};a.tosrus.defaults.drag=a.tosrus.support.touch;a.tosrus.addons.push("drag")}})(jQuery);
(function(a){var l=false,d;a.tosrus.prototype._addon_keys=function(){if(!l){d=a.tosrus._e;d.add("keyup");l=true}var m=this,g=this.opts.keys;if(typeof g=="boolean"&&g)g={prev:true,next:true,close:true};if(a.isPlainObject(g)){for(var j in a.tosrus.constants.keys)if(typeof g[j]=="boolean"&&g[j])g[j]=a.tosrus.constants.keys[j];if(this.nodes.$slides.length<2){g.prev=false;g.next=false}a(document).on(d.keyup,function(e){if(m.vars.opened){var f=false;switch(e.keyCode){case g.prev:f=d.prev;break;case g.next:f=
d.next;break;case g.close:f=d.close;break}if(f){e.preventDefault();e.stopPropagation();m.nodes.$wrpr.trigger(f)}}})}};a.tosrus.defaults.keys=false;a.tosrus.constants.keys={prev:37,next:39,close:27};a.tosrus.addons.push("keys")})(jQuery);
(function(a){var l=false,d,m,g;a.tosrus.prototype._addon_pagination=function(){if(!l){d=a.tosrus._c;m=a.tosrus._d;g=a.tosrus._e;d.add("pagination selected uibg bullets thumbnails");l=true}var j=this,e=this.opts.pagination;typeof e=="boolean"&&a.tosrus.deprecated('A boolean for the option "pagination"','the option "pagination.add"');typeof e=="string"&&a.tosrus.deprecated('A string for the option "pagination"','the option "pagination.target"');e instanceof a&&a.tosrus.deprecated('A jQuery object for the option "pagination"',
'the option "pagination.target"');if(this.nodes.$slides.length<2)e.add=false;if(e.add){if(typeof e.target=="string")e.target=a(e.target);if(e.target instanceof a)this.nodes.$pagr=e.target;else{this.nodes.$pagr=a('<div class="'+d.pagination+" "+d[e.type]+'" />').appendTo(this.nodes.$wrpr);if(!this.nodes.$uibg)this.nodes.$uibg=a('<div class="'+d.uibg+'" />').prependTo(this.nodes.$wrpr)}if(typeof e.anchorBuilder!="function")switch(e.type){case "thumbnails":e.anchorBuilder=this.vars.fixed?function(){return'<a href="#" style="background-image: url('+
a(this).data(m.anchor).attr("href")+');"></a>'}:function(){return'<a href="#" style="background-image: url('+a(this).find("img").attr("src")+');"></a>'};break;case "bullets":default:e.anchorBuilder=function(){return'<a href="#"></a>'};break}this.nodes.$slides.each(function(f){a(e.anchorBuilder.call(this,f+1)).appendTo(j.nodes.$pagr).on(g.click,function(i){i.preventDefault();i.stopPropagation();j.nodes.$wrpr.trigger(g.slideTo,[f])})});this.updatePagination();this.nodes.$wrpr.on(g.sliding,function(){j.updatePagination()})}};
a.tosrus.prototype.updatePagination=function(){this.nodes.$pagr&&this.nodes.$pagr.children().removeClass(d.selected).eq(this.slides.index).addClass(d.selected)};a.tosrus.defaults.pagination={add:false,type:"bullets",target:null,anchorBuilder:null};a.tosrus.addons.push("pagination");a.tosrus.ui.push("pagination");a.tosrus.ui.push("bullets");a.tosrus.ui.push("thumbnails")})(jQuery);
(function(a){a.tosrus.media.html={filterAnchors:function(l){return l.slice(0,1)=="#"&&a(l).is("div")},initAnchors:function(l,d){a('<div class="'+a.tosrus._c("html")+'" />').append(a(d)).appendTo(l);l.removeClass(a.tosrus._c.loading).trigger(a.tosrus._e.loaded)},filterSlides:function(l){return l.is("div")},initSlides:function(){}}})(jQuery);
(function(a){a.tosrus.media.image={filterAnchors:function(l){return a.inArray(l.toLowerCase().split(".").pop().split("?")[0],["jpg","jpe","jpeg","gif","png"])>-1},initAnchors:function(l,d){a('<img border="0" />').on(a.tosrus._e.load,function(m){m.stopPropagation();l.removeClass(a.tosrus._c.loading).trigger(a.tosrus._e.loaded)}).appendTo(l).attr("src",d)},filterSlides:function(l){return l.is("img")},initSlides:function(){}}})(jQuery);
(function(a){function l(c){function h(){if(k.length){k.attr("src","");k.attr("src",o)}}if(!g){j=a[d]._c;e=a[d]._d;f=a[d]._e;i=a[d]._f;b=a[d]._g;e.add("ratio maxWidth maxHeight");g=true}var k=c.children(),n=c.data(a[d]._d.anchor)||a(),o=k.attr("src"),p=n.data(e.ratio)||this.opts[m].ratio,q=n.data(e.maxWidth)||this.opts[m].maxWidth,r=n.data(e.maxHeight)||this.opts[m].maxHeight;c.removeClass(j.loading).trigger(f.loaded).on(f.loading,function(){i.resizeRatio(k,c,q,r,p)});this.nodes.$wrpr.on(f.sliding,
function(){h()}).on(f.closing,function(){h()});b.$wndw.on(f.resize,function(){i.resizeRatio(k,c,q,r,p)})}var d="tosrus",m="vimeo",g=false,j,e,f,i,b;a[d].media[m]={filterAnchors:function(c){return c.toLowerCase().indexOf("vimeo.com/")>-1},initAnchors:function(c,h){var k=this._uniqueID();h=h.split("vimeo.com/")[1].split("?")[0]+"?api=1&player_id="+k;a('<iframe id="'+k+'" src="//player.vimeo.com/video/'+h+'" frameborder="0" allowfullscreen />').appendTo(c);l.call(this,c)},filterSlides:function(c){if(c.is("iframe")&&
c.attr("src"))return c.attr("src").toLowerCase().indexOf("vimeo.com/video/")>-1;return false},initSlides:function(c){l.call(this,c)}};a[d].defaults[m]={ratio:16/9,maxWidth:false,maxHeight:false}})(jQuery);
(function(a){function l(c){function h(r){k.length&&k[0].contentWindow.postMessage('{ "event": "command", "func": "'+r+'Video" }',"*")}if(!g){j=a[d]._c;e=a[d]._d;f=a[d]._e;i=a[d]._f;b=a[d]._g;e.add("ratio maxWidth maxHeight");g=true}var k=c.children(),n=c.data(a[d]._d.anchor)||a(),o=n.data(e.ratio)||this.opts[m].ratio,p=n.data(e.maxWidth)||this.opts[m].maxWidth,q=n.data(e.maxHeight)||this.opts[m].maxHeight;c.removeClass(j.loading).trigger(f.loaded).on(f.loading,function(){i.resizeRatio(k,c,p,q,o)});
this.nodes.$wrpr.on(f.sliding,function(){h("pause")}).on(f.closing,function(){h("stop")});b.$wndw.on(f.resize,function(){i.resizeRatio(k,c,p,q,o)})}var d="tosrus",m="youtube",g=false,j,e,f,i,b;a[d].media[m]={filterAnchors:function(c){return c.toLowerCase().indexOf("youtube.com/watch?v=")>-1},initAnchors:function(c,h){var k=h;h=h.split("?v=")[1].split("&")[0];if(this.opts[m].imageLink){h="//img.youtube.com/vi/"+h+"/0.jpg";a('<a href="'+k+'" class="'+a[d]._c("play")+'" target="_blank" />').appendTo(c);
a('<img border="0" />').on(a[d]._e.load,function(n){n.stopPropagation();c.removeClass(a[d]._c.loading).trigger(a[d]._e.loaded)}).appendTo(c).attr("src",h)}else{a('<iframe src="//www.youtube.com/embed/'+h+'?enablejsapi=1" frameborder="0" allowfullscreen />').appendTo(c);l.call(this,c)}},filterSlides:function(c){if(c.is("iframe")&&c.attr("src"))return c.attr("src").toLowerCase().indexOf("youtube.com/embed/")>-1;return false},initSlides:function(c){l.call(this,c)}};a[d].defaults[m]={ratio:16/9,maxWidth:false,
maxHeight:false,imageLink:a[d].support.touch}})(jQuery);
